### ISSUE TITLE
FlyCasual 2.5 UO Roadmap

### ISSUE THREAD

**Issue by Baledin** [Baledin/FlyCasual#39]
Welcome to the roadmap for Fly Casual 2.5 UO. I will be updating this roadmap throughout development, adding and sometimes even removing features. Please post feature requests on the Fly Casual GitHub repo linked here.

Remember, this is a fan supported project. I have a full-time job and family as well as other commitments and will improve things as time permits.

### Upcoming Features
- [ ] Online support
  - [x] Peer to Peer
  - [ ] Matchmaking
  - [ ] Server browser
- [ ] Implement missing ships/pilots/upgrades (see below)
- [ ] Fix/implement ruleset to be consistent with 2.5 release
  - [x] #14 
  - [ ] Implement ROAD
  - [ ] Implement Scenarios
  - [ ] Alternate scoring/deficit points
  - [x] #63
- [x] #427 
- [ ] Epic rules and ships
- [ ] Game logging
- [ ] Enhanced debugging tools
- [x] #173

### Ships/Pilots to be implemented
**Rebel**
  - [ ] YT-2400 Light Freighter
    - [ ] "Leebo" - Dry-Witted Droid
    - [ ] "Leebo" - He Thinks He's Funny
    - [ ] Dash Rendar - Hotshot Mercenary
    - [ ] Dash Rendar - In it for Himself
	
**Scum**
  - [ ] Customised YT-1300 Light Freighter
    - [ ] Han Solo - Armed and Dangerous
  - [ ] Fang Fighter
    - [ ] Fenn Rau - Armed and Dangerous  
  - [ ] Firespray-class Patrol Craft
    - [ ] Boba Fett - Armed and Dangerous
  - [ ] G-1A Starfighter
    - [ ] Zuckuss - Armed and Dangerous
  - [ ] Gauntlet fighter
    - [ ] Bo-Katan Kryze - Armed and Dangerous
  - [ ] Jumpmaster 3000
    - [ ] Dengar - Armed and Dangerous
  - [ ] Naboo Royal N-1
    - [ ] The Mandalorian - Armed and Dangerous
  - [ ] Rogue-class Starfighter
    - [ ] Cad Bane - Armed and Dangerous
  - [ ] StarViper-class Attack Platform
    - [ ] Prince Xizor - Armed and Dangerous
  - [ ] YT-2400 Light Freighter
    - [ ] Dash Rendar - In it for Himself
    - [ ] "Leebo" - He Thinks He's Funny
  - [ ] YV-666 Light Freighter 
    - [ ] Bossk - Armed and Dangerous

**First Order**
  - [x] TIE/Fo Fighter
    - [x] #418 
    - [x] #419
    - [x] #420
    - [x] #421
    - [x] #415 
  - [ ] TIE/se Bomber
    - [ ] "Grudge"
  - [x] TIE/sf Fighter
    - [x] #436
    - [x] #422 
    - [x] #430
  - [x] TIE/vn Silencer
    - [x] #413 
  - [ ] Upsilon class Command Shuttle
    - [ ] #477 

**Resistance**
  - [ ] MG-100 StarFortress
    - [ ] Finch Dallow - Evacuation of D'Qar
    - [ ] Vennie - Evacuation of D'Qar
  - [ ] Resistance Transport
    - [ ] Pammich Nero Goode - Evacuation of D'Qar   
  - [x] RZ-2 A-Wing
    - [x] #471
    - [x] #446 
    - [x] #447 
  - [x] T-70 X-Wing
    - [x] #478  
    - [x] #444 
    - [x] #443 
    - [x] #438 

**Republic**
  - [ ] Eta-2 Actis
    - [ ] Anakin Skywalker - Siege of Coruscant
    - [ ] Obi-Wan Kenobi - Siege of Coruscant
    - [ ] Shaak Ti - Siege of Coruscant
  - [ ] Nimbus-class V-Wing
    - [ ] "Contrail" - Siege of Coruscant
    - [ ] "Klick" - Siege of Coruscant
  - [ ] Syliure-class Hyperspace Ring
    - [ ] TransGalMeg Control Link
  - [ ] V-19 Torrent Starfighter
    - [ ] "Axe" - Siege of Coruscant
    - [ ] "Kickback" - Siege of Coruscant

### Upgrades to be implemented
**Cargo**
  - [ ] Adaptive Shields
  - [ ] Boosted Scanners
  - [ ] Optimized Power Core
  - [ ] Tibanna Reserves

**Command**
  - [ ] Agent of the Empire
  - [ ] Bounty
  - [ ] Dreadnaught Hunter
  - [ ] First Order Elite
  - [ ] In it for the Money / Rebellion
  - [ ] Jedi Commander
  - [ ] Phoenix Squadron
  - [ ] Shadow Wing
  - [ ] Skystrike Academy Class
  - [ ] Veteran Wing Leader

**Command/Configuration**
  - [ ] Combat Boarding Tube (Gauntlet)

**Command/Crew**
  - [ ] Admiral Ozzel
  - [ ] Asajj Ventress
  - [ ] Azmorigan
  - [ ] Captain Needa
  - [ ] Carlist Rieekan
  - [ ] General Grievous
  - [ ] Hondo Ohnaka
  - [ ] Jan Dodonna
  - [ ] Mar Tuuk
  - [ ] Raymus Antilles
  - [ ] Riff Tamson
  - [ ] Stalwart Captain
  - [ ] Strategic Commander
  - [ ] Zealous Captain
  
**Command/Title**
  - [ ] B6 Blade Wing Prototype (Epic)
  
**Configuration**
  - [ ] Corsair Refit

**Crew**
  - [ ] Gar Saxon (Empire)
  - [ ] Greef Karga (Scum)
  - [ ] IG-11 (Scum)
  - [ ] Korkie Kryze (Republic)
  - [ ] Kuill (Scum)
  - [ ] Obi-Wan Kenobi (Republic)
  - [ ] Peli Motto (Scum)
  - [ ] Pre Vizsla (Scum/Separatist)
  - [ ] Prime Minister Almec (Republic/Scum)
  - [ ] Satine Kryze (Republic)
  - [x] #457
  - [ ] Tal Merrik (Separatist)
  - [ ] Toryn Farr

**Crew/Crew**
  - [ ] Clan Wren Commando Team (Rebel)
  - [ ] Death Watch Commando Team (Separatist)
  - [ ] Imperial Super Commando Team (Imperial)
  - [ ] Mandalorian Super Commando Team (Scum)
  - [ ] Maul (Scum)
  - [ ] Nite Owl Commando Team (Republic)

**Gunner**
  - [ ] Migs Mayfield (Imperial/Scum)
  - [ ] Paige Tico (Resistance)
  
**Hardpoint**
  - [ ] Ion Cannon Battery
  - [ ] Ordnance Tubes
  - [ ] Point-Defense Battery
  - [ ] Targeting Battery
  - [ ] Tractor Tentacles
  - [ ] Turbolaser Battery
  
**Hardpoint/Cargo**
  - [ ] Drill Beak
  - [ ] Enhanced Propulsion
  - [ ] Proton Cannon Battery

**Illicit**
  - [ ] Quick-Release Locks
  - [ ] Saboteur's Map
  - [ ] Scanner Baffler
  - [ ] Tracking Fob

**Modification**
  - [ ] #151 

**Payload**
  - [ ] Blazer Bomb

**Talent**
  - [ ] Feedback Ping
  
**Team**
  - [ ] Bombardment Specialists
  - [ ] Comms Team
  - [ ] Damage Control Team
  - [ ] Droid Crew
  - [ ] Gunnery Specialists
  - [ ] IG-RM Droids
  - [ ] Ordinance Team
  - [ ] Senor Experts
  - [ ] Tractor Technicians

**Team/Gunner**
  - [ ] Corsair Crew

**Title**
  - [ ] Assailer
  - [ ] Blood Crow
  - [ ] Bright Hope
  - [ ] Broken horn
  - [ ] Corvus
  - [ ] Dodonna's Pride
  - [ ] Grappler
  - [ ] Impetuous
  - [ ] Insatiable Worrt
  - [ ] Instigator
  - [ ] Jaina's Light
  - [ ] Liberator
  - [ ] Luminous
  - [ ] Merchant One
  - [ ] Nautolan's Revenge
  - [ ] Neimoidian Grasp
  - [ ] Quantum Storm
  - [ ] Requiem
  - [ ] Suppressor
  - [ ] Tantive IV
  - [ ] Thunderstrike
  - [ ] TIE Defender Elite
  - [ ] Trident
  - [ ] Vector

**Torpedo**
  - [ ] Tracking Torpedoes
  
### Epic Ships/Pilots
**Imperial**
  - [ ] Gozanti-class Cruiser
    - [ ] Rik Virgilio - Blood Crow
	- [ ] Outer Rim Garrison
  - [ ] Raider-class Corvette
    - [ ] Iden Versio - Corvus
	- [ ] Outer Rim Patrol

**Rebel**
  - [ ] CR-90 Corvette
    - [ ] Raymus Antilles - Tantive IV
	- [ ] Alderaanian Guard
  - [ ] GR-75 Medium Transport
    - [ ] Trebor Zednem - Bright Hope
	- [ ] Echo Base Evacuees

**Scum**
  - [ ] C-ROC Cruiser
    - [ ] Cikatro Vizago - Broken Horn
	- [ ] Syndicate Smugglers
  - [ ] Trident-class Assault Ship
    - [ ] Sorc Tormo - Nautolan's Revenge
	- [ ] Lawless Pirates

**First Order**
  - [ ] Gozanti-class Cruiser
    - [ ] Cerra Fellian - Malefactor
	- [ ] First Order Sympathizers
  - [ ] Raider-class Corvette
    - [ ] Gideon Hask - Precursor
	- [ ] First Order Collaborators

**Resistance**
  - [ ] CR-90 Corvette
    - [ ] Leia Organa - Tantive IV
  - [ ] GR-75 Medium Transport
    - [ ] Orag Desyk - Hosnian Lament
	- [ ] New Republic Volunteers

**Republic**
  - [ ] CR-90 Corvette
    - [ ] Raymus Antilles - Tantive IV
	- [ ] Republic Judiciary
  - [ ] Gozanti-class Cruiser
    - [ ] Wez Synat - Spectre of Nayr

**Separatist**
  - [ ] C-ROC Cruiser
    - [ ] Separatist Privateers
  - [ ] Gozanti-class Cruiser
    - [ ] Aut-0 - Alpha Revue
  - [ ] Trident-class Assault Ship
    - [ ] Asajj Ventress - Trident
	- [ ] Colicoid Destroyer

**Comment by MUGNERCL** [comment]
Could you consider the 2 below:
- 2.5 Mission points (I understand this would be a great challenge for the IA)
- Pre-made IA squad (This exist in Legacy and I find it very handy)

**Comment by Baledin** [comment]
> Could you consider the 2 below:
> 
> * 2.5 Mission points (I understand this would be a great challenge for the IA)
> * Pre-made IA squad (This exist in Legacy and I find it very handy)

Please add a new Enhancement issue and we can take it under advisement!

**Comment by quall3** [comment]
Hey, do you have any intention of implementing mandalorian supercommando remotes and the drop seat bay Mod upgrade?

**Comment by Baledin** [comment]
> Hey, do you have any intention of implementing mandalorian supercommando remotes and the drop seat bay Mod upgrade?

I do indeed, I didn't realize they weren't on my Roadmap. I'll add them now.

**Comment by quall3** [comment]
Dont forget the double crew upgrade to drop the commando remotes ;)
that is a separate upgrade for each of 
rebel
empire
scum
republic
separatists

**Comment by Baledin** [comment]
@quall3 I just ran through the entire list from the latest points release and updated the roadmap to include all upgrades that aren't currently included. I believe that includes all of the ones that you had mentioned.

**Comment by Baledin** [comment]
Updated, adding Epic ships to items to implement

**Comment by Baledin** [comment]
Moved Epic ships/pilots to the end of the list as they will be focused on after most other pilots/upgrades are added.

**Comment by Baledin** [comment]
Updated Roadmap to remove pilots/upgrades that have been released for awhile now.
